### ISSUE TITLE
Bring in pattern noise image

### ISSUE THREAD

**Issue by noqsi** [TESScience/httm#59]
If there is pattern noise, we'll get the pattern noise image from calibration as a FITS file. Commit f4018fea322958be496b7b24af7be16f5c3dd1b implements such a test image. But right now, we assume it's a .npz file. We either need to change this, or have a tool to convert.

**Comment by xcthulhu** [comment]
We can just support both, it's not a big deal.

Just send a FITS file and I'll write something that reads it in instead of the npz file.

**Comment by noqsi** [comment]
TODO:

- Run `make_spot50_pattern` script
- Hand `make_spot50_pattern` FITS in ipython notebook
